# Generated by Django 3.0.5 on 2021-10-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(error_messages={'unique': 'Такой ингридиент уже создан'}, max_length=200, unique=True, verbose_name='Название ингридиента')),
                ('measurement_unit', models.TextField(max_length=200, verbose_name='единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название тега')),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.TextField(max_length=200, unique=True, verbose_name='Название блюда')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления в минутах')),
                ('ingredients', models.ManyToManyField(related_name='all_recipes', to='recipes.Ingredients')),
                ('tags', models.ManyToManyField(related_name='tags', to='recipes.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Если количество выбирается по вкусу, впишите здесь ноль')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_ingredients', to='recipes.Recipes')),
            ],
        ),
    ]
