# Generated by Django 3.0.5 on 2021-11-09 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(default=1, help_text='Если количество выбирается по вкусу, впишите здесь 1', validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть больше ноля')]),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Название блюда'),
        ),
    ]
