# Generated by Django 3.0.5 on 2021-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211009_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(default=1, help_text='Если количество выбирается по вкусу, впишите здесь ноль'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together={('recipe', 'name')},
        ),
    ]
