# Generated by Django 3.0.5 on 2021-10-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ingredientamount_ingredients_recipes_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.DeleteModel(
            name='IngredientAmount',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
